# Generated by Django 5.1.6 on 2025-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('school', models.CharField(default='NYU', max_length=255)),
                ('grade', models.CharField(default='Freshman', max_length=20)),
            ],
        ),
    ]
