# Generated by Django 5.1.6 on 2025-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_rename_restaurant_menus_restaurant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$XaDd3sBCZaOiNm0m7aPhq2$GxzqoaIJag7rKJAObnyuVAsKBb7k6kEjlmxUv9CioPc=",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="school",
            field=models.CharField(default="NYU", max_length=255),
        ),
    ]
