# Generated by Django 5.1.6 on 2025-04-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_restaurant_menus_restaurant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
