# Generated by Django 5.1.6 on 2025-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_alter_users_password_alter_users_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$n1YKgVAMrQZeERZ3n9nH4V$NmLz1CS0pd9KDCiXiX8EpusrQyyTzhfg64MiqBgdB3c=",
                max_length=255,
            ),
        ),
    ]
